on:
  workflow_call:

    inputs:
      service-name:
        required: true
        type: string
      environment:
        required: true
        type: string
      cluster-name:
        required: true
        type: string
      repository:
        required: true
        type: string
      ecr-repository:
        required: true
        type: string
      environment-file:
        required: false
        type: string
      is-scheduled-task:
        required: false
        type: boolean

    secrets:
      aws-account-id:
        required: true
      region:
        required: true
      access-key-id:
        required: true
      secret-access-key:
        required: true
      personal-access-token:
        required: true
      github-token:
         required: true
      git-admin-user:
        required: false
      version-major:
        required: true
      version-minor:
        required: true
      version-hotfix:
        required: true
      version-build:
        required: true
      last-preview-build:
        required: false
jobs:
  update_version:
    uses: ./.github/workflows/UpdateBuildVersion.yml
    with:
      service-name: ${{ inputs.service-name }}
      environment: ${{ inputs.environment }}
      repository: ${{ inputs.repository }}
      environment-file: ${{ inputs.environment-file }}
    secrets:
      personal-access-token: ${{ secrets.personal-access-token }}
      github-token: ${{ secrets.github-token }}
      version-major: ${{ secrets.version-major }}
      version-minor: ${{ secrets.version-minor }}
      version-hotfix: ${{ secrets.version-hotfix }}
      version-build: ${{ secrets.version-build }}
      last-preview-build: ${{ secrets.last-preview-build }}

  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '3.x'
        # Optional - x64 or x86 architecture, defaults to x64
        architecture: 'x64'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.access-key-id }}
        aws-secret-access-key: ${{ secrets.secret-access-key }}
        aws-region: ${{ secrets.region }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      with:
        mask-password: 'true'

    
    - name: Build, tag and push
      id: build-image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Render in the new image ID in the ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: TaskDefinitions/task-definition-${{ inputs.environment }}.json
        container-name: ${{ inputs.service-name }}
        image: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

    - name: Deploy ECS task definition
      if: ${{ inputs.is-scheduled-task == false || inputs.is-scheduled-task == '' || inputs.is-scheduled-task == null  }}
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: ${{ inputs.service-name }}
        cluster: ${{ inputs.cluster-name }}
        wait-for-service-stability: false

    # Specific deployment for Scheduled Tasks
    - name: Deploy to ECS Scheduled Tasks
      if: ${{ inputs.is-scheduled-task == true  }}
      uses: airfordable/ecs-deploy-task-definition-to-scheduled-task@v2.0.0
      with:
        cluster: ${{ inputs.cluster-name }}
        task-definition: ${{ steps.task-def.outputs.task-definition }}

