on:
  workflow_call:
    
    inputs:
      environment:
        required: true
        type: string
      cluster-name:
        required: false
        type: string
      aws-account-id: 
        required: false
        type: string

    secrets:
      region:
        required: true

jobs:
  update_version:
    uses: ./.github/workflows/UpdateBuildVersion.yml
    with:
      environment: staging

  deploy:
    name: Display inputs
    runs-on: ubuntu-latest
    needs: update_version
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Display Environment
        run: echo "Environment is ${{ inputs.environment }}."

      - name: Display Cluster
        run: echo "Cluster is ${{ inputs.cluster-name }}."

      - name: AWS Account ID
        run: echo "AWS Account ID ${{ inputs.aws-account-id }}"

      - name: AWS Region
        run: echo "AWS Region ${{ secrets.region }}"

      - name: Display Secrets Build Version
        run: echo "Updated build version ${{ needs.update_version.outputs.updated_build_version }}"