on:
  workflow_call:
    
    inputs:
      environment:
        required: true
        type: string
      cluster-name:
        required: false
        type: string

    secrets:
      aws-account-id: 
        required: false
      region:
        required: true
      personal-access-token:
        required: true
      github-token:
         required: true
      version-major:
        required: true
      version-minor:
        required: true
      version-hotfix:
        required: true
      version-build:
        required: true

jobs:
  # update_version:
  #   uses: ./.github/workflows/UpdateBuildVersionTest.yml
  #   with:
  #     environment: staging

  deploy:
    name: Display inputs
    runs-on: ubuntu-latest
    env:
      FORMATTED_ENVIRONMENT: null
    #needs: update_version
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check for Preview
        if: ${{ inputs.environment == 'preview' }}
        run: echo "FORMATTED_ENVIRONMENT=Preview" >> $GITHUB_ENV 
      
      - name: Check for Staging
        if: ${{ inputs.environment == 'staging' }}
        run: run: echo "FORMATTED_ENVIRONMENT=Staging" >> $GITHUB_ENV
      
      - name: Check for Production
        if: ${{ inputs.environment == 'production' }}
        run: run: echo "FORMATTED_ENVIRONMENT=Production" >> $GITHUB_ENV 
      
      - name: Show Formmated Environment
        run: echo "Formatted Environment is ${{ env.FORMATTED_ENVIRONMENT }}"