on:
  workflow_call:

    inputs:
      ecr-repository:
        required: true
        type: string
      lambda-function-name:
        required: true
        type: string
      build-args:
        required: true
        type: string

    secrets:
      aws-account-id:
        required: true
      region:
        required: true
      access-key-id:
        required: true
      secret-access-key:
        required: true
      git-admin-user:
        required: true
      git-token:
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x' # SDK Version to use; x will use the latest version of the 3.1 channel
    - name: Build
      run: |
          dotnet nuget add source --username ${{ secrets.git-admin-user }} --password ${{ secrets.git-token }} --store-password-in-clear-text --name LoadriteFeed "https://nuget.pkg.github.com/Trimble-Insight/index.json"
          dotnet build --configuration Release
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.access-key-id }}
        aws-secret-access-key: ${{ secrets.secret-access-key }}
        aws-region: ${{ secrets.region }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      with:
        mask-password: 'true'

    - name: Build, tag, and push image to ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ secrets.aws-account-id }}.dkr.ecr.${{ secrets.region }}.amazonaws.com
        ECR_REPOSITORY: ${{ inputs.ecr-repository }}
        IMAGE_TAG: latest
      run: |
        # Build a docker container and
        # push it to ECR so that it can
        # be deployed to ECS.
        docker build . -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG --build-arg ${{inputs.build-args}}
        docker push "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

    - name: Update AWS Lambda Function Code
      env:
        IMAGE_URI: ${{ steps.build-image.outputs.image }}
      run: |
        aws lambda update-function-code --function-name arn:aws:lambda:${{ secrets.region }}:${{ secrets.aws-account-id }}:function:${{ inputs.lambda-function-name }} --image-uri $IMAGE_URI
