on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      cluster-name:
        required: false
        type: string
      version-build:
        required: false
        type: string

jobs:
  deploy:
    name: Display inputs
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Display Environment
        run: echo "Environment is ${{ inputs.environment }}."

      - name: Display Cluster
        run: echo "Cluster is ${{ inputs.cluster-name }}."
      
      - name: Display Build Version
        run: echo "Build version ${{ inputs.version-build }}"
