# on:
#   pull_request:
#     branches: [release/preview]
#     types: [opened, synchronize]

# jobs:
#   deploy:
#     name: Deploy to Preview
#     runs-on: ubuntu-latest
#     environment: preview

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2

#       call-workflow-passing-data:
#         uses: ./.github/workflows/Deploy.yml
#         with:
#           environment: preview
#           cluster-name: preview-cluster

name: Call a reusable workflow

on:
  pull_request:
    branches:
      - release/preview

jobs:

  call-workflow-passing-data:
    uses: ./.github/workflows/Deploy.yml
    with:
      environment: preview
      cluster-name: preview-cluster