# name: Call a reusable workflow

# on:
#   pull_request:
#     branches: [release/preview]
#     types: [opened, synchronize]

# jobs:

#   call-workflow-passing-data:
#     uses: ./.github/workflows/Deploy.yml
#     with:
#       environment: preview
#       cluster-name: preview-cluster

name: Call a reusable workflow

on:
  pull_request:
    branches: [release/preview]
    types: [opened, synchronize]

jobs:

  steps:
  - name: Call Workflow Passing Data
    uses: ./.github/workflows/Deploy.yml
    with:
      environment: preview
      cluster-name: preview-cluster