on:
  pull_request:
    branches: [release/preview]
    types: [opened, synchronize]

jobs:
  deploy:
    name: Deploy to Preview
    runs-on: ubuntu-latest
    environment: preview

    steps:
      - name: First Step
        uses: Trimble-Insight/reusable-workflow/.github/workflows/Deploy.yml
        with:
          environment: preview
          cluster-name: preview-cluster