# name: Call a reusable workflow

# on:
#   pull_request:
#     branches: [release/preview]
#     types: [opened, synchronize]

# jobs:

#   call-workflow-passing-data:
#     uses: ./.github/workflows/Deploy.yml
#     with:
#       environment: preview
#       cluster-name: preview-cluster

name: Call a reusable workflow

on:
  pull_request:
    branches: [release/preview]
    types: [opened, synchronize]

jobs:
  set_versioning:
    runs-on: ubuntu-latest
    outputs:
      version_build: ${{ steps.set-build-version.outputs.version_build }}
    steps:
      - name: Set Build Version
        id: set-build-version
        run: echo "::set-output name=version_build::2"

  deploy_to_preview:
    needs: set_versioning
    uses: ./.github/workflows/Deploy.yml
      with:
        environment: preview
        cluster-name: preview-cluster
        version-build: ${{ needs.set_versioning.outputs.version_build }}
      
  
  # concurrent-job:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Show concurrency
  #       run: echo "Concurrency..."