name: Call a reusable workflow

on:
  pull_request:
    branches: [release/preview]
    types: [opened, synchronize]

jobs:
  # set_versioning:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     version_build: ${{ steps.set-build-version.outputs.version_build }}
  #   steps:
  #     - name: Set Build Version
  #       id: set-build-version
  #       run: echo "::set-output name=version_build::2"

  deploy_to_preview:
    if: ${{ false }}
    uses: ./.github/workflows/DeployTest.yml
    with:
      environment: preview
      cluster-name: preview-cluster
    secrets:
      aws-account-id: ${{ secrets.LR_AWS_ACCOUNT_ID }}
      region: ${{ secrets.LR_AWS_PREVIEW_REGION }}
      personal-access-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      github-token: ${{ secrets.GITHUB_TOKEN }}
      version-major: ${{ secrets.VERSION_MAJOR }}
      version-minor: ${{ secrets.VERSION_MINOR }}
      version-hotfix: ${{ secrets.VERSION_HOTFIX }}
      version-build: ${{ secrets.VERSION_BUILD }}
      
  
  # concurrent-job:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Show concurrency
  #       run: echo "Concurrency..."