name: Set Build Version

on:
  workflow_call:
    outputs:
      build_version:
        description: "Build version"
        value: ${{ jobs.set_version.outputs.output_build_version }}
  
jobs:
  set_version:
    runs-on: ubuntu-latest
    outputs:
      output_build_version: ${{ steps.set-version.outputs.build_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Build Version
        id: set-version
        env:
          VERSION_BUILD: ${{secrets.VERSION_BUILD}}
        run: |
          echo ::set-output name=build_version::$((VERSION_BUILD + 1))