name: Test Deploy

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]
  
jobs:
  configure:
    uses: ./.github/workflows/TestFlow.yml
    with:
      some-input: CognitoLambdaTest


  deploy:
    needs: configure
    uses: Trimble-Insight/reusable-workflow/.github/workflows/DeployTest.yml@main
    with:
      environment: preview
    secrets:
      aws-account-id: ${{ secrets.LR_AWS_ACCOUNT_ID }}
      region: ${{ secrets.LR_AWS_PREVIEW_REGION }}
      personal-access-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      github-token: ${{ secrets.GITHUB_TOKEN }}
      version-major: ${{ secrets.VERSION_MAJOR }}
      version-minor: ${{ secrets.VERSION_MINOR }}
      version-hotfix: ${{ secrets.VERSION_HOTFIX }}
      version-build: ${{ secrets.VERSION_BUILD }}