on:
  workflow_call:
    inputs:
      some-input:
        required: false
        type: string

jobs:
  configure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Echo
        run: echo "Testing The Flow!"