name: Set Build Version

on:
  workflow_call:
    inputs:
      service-name:
        required: false
        type: string
      environment:
        required: true
        type: string
      repository:
        required: true
        type: string
      environment-file:
        required: false
        type: string
    secrets:
      personal-access-token:
        required: true
      github-token:
        required: true
      version-major:
        required: true
      version-minor:
        required: true
      version-hotfix:
        required: true
      version-build:
        required: true
      last-preview-build:
        required: false

jobs:
  update_version_preview:
    if: ${{ inputs.environment == 'preview' }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      VERSION: null
      VERSION_MAJOR: ${{ secrets.version-major }}
      VERSION_MINOR: ${{ secrets.version-minor }}
      VERSION_HOTFIX: ${{ secrets.version-hotfix }}
      VERSION_BUILD: ${{ secrets.version-build }}
      LAST_PREVIEW_BUILD: ${{ secrets.last-preview-build }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set build version
        id: increment-build
        env:
          VERSION_BUILD: ${{env.VERSION_BUILD}}
        run: echo "updated-build-version=$((VERSION_BUILD + 1))" >> $GITHUB_OUTPUT

      - name : Increment VERSION_BUILD
        uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'VERSION_BUILD'
          value: ${{ steps.increment-build.outputs.updated-build-version }}
          repository: 'Trimble-Insight'
          token: ${{ secrets.personal-access-token }}
          org: true
          visibility: 'private'

      - name : Set LAST_PREVIEW_BUILD
        uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'LAST_PREVIEW_BUILD'
          value: ${{ steps.increment-build.outputs.updated-build-version }}
          repository: ${{ inputs.repository }}
          token: ${{ secrets.personal-access-token }}
          visibility: 'private'

      - name: Set environment variable with version
        run: echo "VERSION=v${{env.VERSION_MAJOR}}.${{env.VERSION_MINOR}}.${{env.VERSION_HOTFIX}}.${{steps.increment-build.outputs.updated-build-version}}" >> $GITHUB_ENV

      - name: Set updated build number to file
        shell: bash
        run: expr ${{ env.VERSION }} > version.txt

      - name: Upload version artifact
        uses: actions/upload-artifact@v4
        with:
          name: version
          path: version.txt

      - name: Tag commit
        uses: rickstaa/action-create-tag@v1.6.1
        with:
          github_token: "${{ secrets.github-token }}"
          tag: "${{ env.VERSION }}"

  update_version_staging:
    if: ${{ inputs.environment == 'staging' }}
    runs-on: ubuntu-latest
    env:
      VERSION: v${{secrets.version-major}}.${{secrets.version-minor}}.${{secrets.version-hotfix}}.${{secrets.last-preview-build}}-stg

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set updated build number to file
        shell: bash
        run: expr ${{ env.VERSION }} > version.txt

      - name: Upload version artifact
        uses: actions/upload-artifact@v4
        with:
          name: version
          path: version.txt

      - name: Tag commit
        uses: rickstaa/action-create-tag@v1.6.1
        with:
          github_token: "${{ secrets.github-token }}"
          tag: ${{ env.VERSION }}

  update_version_production:
    if: ${{ inputs.environment == 'production' }}
    runs-on: ubuntu-latest
    env:
      VERSION: v${{secrets.version-major}}.${{secrets.version-minor}}.${{secrets.version-hotfix}}.${{secrets.version-build}}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set updated build number to file
        shell: bash
        run: expr ${{ env.VERSION }} > version.txt

      - name: Upload version artifact
        uses: actions/upload-artifact@v4
        with:
          name: version
          path: version.txt

      - name: Tag commit
        uses: rickstaa/action-create-tag@v1.6.1
        with:
          github_token: "${{ secrets.github-token }}"
          tag: "${{ env.VERSION }}"
