name: Set Build Version

on:
  workflow_call:
    inputs:
      environment: 
        required: true
        type: string
      repository:
        required: true
        type: string
    secrets:
      personal-access-token:
        required: true
      github-token:
        required: true
      version-major:
        required: true
      version-minor:
        required: true
      version-hotfix:
        required: true
      version-build:
        required: true
      last-preview-build:
        required: false
  
jobs:
  update_version_preview:
    if: ${{ inputs.environment == 'preview' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Build Version
        id: increment-build
        env:
          VERSION_BUILD: ${{secrets.version-build}}
        run: |
          echo ::set-output name=updated-build-version::$((VERSION_BUILD + 1))
      
      - name : Increment build version - VERSION_BUILD
        uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'VERSION_BUILD'
          value: ${{ steps.increment-build.outputs.updated-build-version }}
          repository: 'Trimble-Insight'
          token: ${{ secrets.personal-access-token }}
          org: true
          visibility: 'private'
      
      - name : Increment build version - LAST_PREVIEW_BUILD
        uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'LAST_PREVIEW_BUILD'
          value: ${{ steps.increment-build.outputs.updated-build-version }}
          repository: ${{ inputs.repository }}
          token: ${{ secrets.personal-access-token }}
          visibility: 'private'

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "Microservice/appsettings.Preview.json"

      - name: Update app settings
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          sed -i "s/<version>/$VERSION/g" Microservice/appsettings.Preview.json
        env:
            VERSION: "v${{secrets.version-major}}.${{secrets.version-minor}}.${{secrets.version-hotfix}}.${{steps.increment-build.outputs.updated-build-version}}"

      # Temp
      - name: Save Output
        uses: pCYSl5EDgo/cat@master
        id: save-output
        with:
          path: Microservice/appsettings.Preview.json

      - name: Show Output
        run: echo $TEXT
        env:
          TEXT: ${{ steps.save-output.outputs.text }}
      # Temp end

      - name: Tag commit
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: "${{ secrets.github-token }}"
          tag: "v${{secrets.version-major}}.${{secrets.version-minor}}.${{secrets.version-hotfix}}.${{steps.increment-build.outputs.updated-build-version}}"

  update_version_staging:
    if: ${{ inputs.environment == 'staging' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "Microservice/appsettings.Staging.json"

      - name: Update app settings
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          sed -i "s/<version>/$VERSION/g" Microservice/appsettings.Staging.json
      
      - name: Tag commit
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: "${{ secrets.github-token }}"
          tag: "v${{secrets.version-major}}.${{secrets.version-minor}}.${{secrets.version-hotfix}}.${{secrets.last-preview-build}}-stg"
  
  update_version_production:
    if: ${{ inputs.environment == 'production' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "Microservice/appsettings.Production.json"

      - name: Update app settings
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          sed -i "s/<version>/$VERSION/g" Microservice/appsettings.Production.json
        env:
          VERSION: "v${{secrets.version-major}}.${{secrets.version-minor}}.${{secrets.version-hotfix}}.${{secrets.version-build}}"
      
      - name: Tag commit
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: "${{ secrets.github-token }}"
          tag: "v${{secrets.version-major}}.${{secrets.version-minor}}.${{secrets.version-hotfix}}.${{secrets.version-build}}"
