name: Update Build Version

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    outputs:
      preview-version:
        description: "Preview Build version"
        value: ${{ jobs.update_version_preview.outputs.output1 }}

jobs:
  update_version_preview:
    if: ${{ inputs.environment == 'preview' }}
    runs-on: ubuntu-latest
    env:
      PREVIEW_VERSION: null
    outputs:
      output1: ${{ steps.set-output.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Environment Variable with Version
        run: echo "PREVIEW_VERSION=v3.0.0.1" >> $GITHUB_ENV

      - name: Set Output with Environment Variable
        id: set-output
        run: echo "version=${{ env.PREVIEW_VERSION }}" >> $GITHUB_OUTPUT

  update_version_staging:
    if: ${{ inputs.environment == 'staging' }}
    runs-on: ubuntu-latest
    steps:
      - name: Display staging
        run: echo "This is the staging process!"